version: "3.1"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "80:80"
  kiosk:
    build: ./kiosk
    command: ./init.sh
    volumes:
      - ./kiosk:/code
      - ./site-library:/usr/local/lib/R/site-library
    ports:
      - "8080:8080"
  ml:
    build: ./ml
    command: ["Rscript","plumb.R"]
    volumes:
      - ./ml:/code
    ports:
      - "8000:8000"